site_name: NBA Ranking App
docs_dir: .
site_dir: site

theme:
  name: mkdocs
  navigation_depth: 3

# Control which Markdown files appear in the site navigation.
# Does not prevent other Markdown files from being built.
nav:
  - Home: README.md
  - Scope: Scope.md
  - Architecture: Architecture.md
  - Milestone-1: Milestone-1.md
  - Milestone-2: Milestone-2.md
  - Milestone-3: Milestone-3.md
  - Screens: Screens.md
#  - Appendix: Appendix.md

# Uncomment exclude_docs to build only the files listed above.
# The first pattern excludes everything, and the ! patterns allow selected files.
# exclude_docs: |
#   *
#   !README.md
#   !Architecture.md

plugins:
#  - search
  - same-dir

markdown_extensions:
  - toc:
      toc_depth: 2-3
